
title: "Lisa's Lessons"
email: lgoeller@hmc.edu
description: >- # this means to ignore newlines until "baseurl:"
  This site acts as a a gallery of my projects, as well as a way for me 
  to discuss my thoughts on whatever I’m interested in at the moment.
baseurl: "" 
url: "https://lgoeller.github.io" 
github_username:  lgoeller

# Build settings
markdown: kramdown
theme: minima
exclude: 
    - posts/
#plugins:
#  - jekyll-feed
show-excerpts: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
